name = "todo-list-app"
main = "src/index.ts"
compatibility_date = "2023-05-05"

kv_namespaces = [
  { binding = "EXAMPLE_TODOS", id = "925964e5c1b14674b915260c5d65a1d0", preview_id = "925964e5c1b14674b915260c5d65a1d0" }
]

[env.preview]
kv_namespaces = [
  { binding = "EXAMPLE_TODOS", id = "f6759e59ae9a48b0bfd391ac89b6a7fd" }
]